### ISSUE TITLE
Apexcharts-card configuration breaks user-created graphs

### ISSUE THREAD

**Issue by 18107** [V2G-liberty/addon-v2g-liberty#156]
Before installing V2G Liberty I was using ApexCharts-Card to display several graphs.
After installing V2G Liberty, these graphs stopped displaying correctly and started throwing errors.

Before:
![Stacked graphs old](https://github.com/user-attachments/assets/ae14c08b-faf3-47d3-a8d6-4cbb5c946c04)
After:
![Stacked graphs new](https://github.com/user-attachments/assets/bd4ef09a-5155-4b52-8ff5-6af158585b0f)
Errors:
![Stacked graphs error](https://github.com/user-attachments/assets/665fc8be-35a1-482f-a434-bb7215d315fe)

**Comment by rhpijnacker** [comment]
Which version of apex-charts are you using via HACS?

**Comment by 18107** [comment]
I was on v2.0.4. Updating to v2.1.2 removed the errors, but did not fix the graphs.

**Comment by 18107** [comment]
Updating to version 2.1.2 and changing
```
apex_config:
  chart:
    stacked: true
```
to
```
stacked: true
```
and adding
```
stack_group: groupName
```
to each entity fixed the issues.

**Comment by ArdJonker** [comment]
You changed the code in your own charts i assume. Thanks for the update, maybe useful to others!
