### ISSUE TITLE
Feature request: Add "unknown" state to real_charge_power and car_state_of_charge sensors

### ISSUE THREAD

**Issue by rhpijnacker** [V2G-liberty/addon-v2g-liberty#170]
When the system cannot communicate with the charger, it is unclear what the "charging power" is.
However, the UI still shows the last state, which could falsely give the impression that charging is still happening.

Would it not be better to show "Unknown" instead?

**Comment by ArdJonker** [comment]
This is also applicable for the SoC

**Comment by ArdJonker** [comment]
This also applies for the SoC when the car is disconnected.

**Comment by ArdJonker** [comment]
Implemented by #184
