### ISSUE TITLE
BUG: Sometimes settings do not get loaded at restart

### ISSUE THREAD

**Issue by ArdJonker** [V2G-liberty/addon-v2g-liberty#25]
Resulting in user settings being "forgotten" and factory defaults to get loaded.

**Comment by johannesdeboer** [comment]
![Screenshot 2024-06-24 at 21 36 34](https://github.com/V2G-liberty/addon-v2g-liberty/assets/65627954/3096db03-935a-45f8-bef0-c980bf82f451)

Issue still occurs sometimes. Especially the settings of :
-  admin mobile name
- Change default (dis-)charge power (switch position is forgotten)
- calendar integration ID.
