### ISSUE TITLE
"Reduce max. (dis-)charge power" setting not preserved

### ISSUE THREAD

**Issue by rhpijnacker** [V2G-liberty/addon-v2g-liberty#71]
I noticed that with the Load Balancer enabled, the charger limits the maximum power to around 4000W even though it is set to 20A (4750W).
So help FM making better schedules, I decided to enter these values in the "Reduce max. (dis-)charge power" fields. However, it seems that after restarting the add-on, this setting always defaults back to disabled.

**Comment by ArdJonker** [comment]
The base problem is that the toggle "Reduce max discharge power" is not preserved. And that is a wider problem: none of the toggles are preserved. So also VAT & Markup and change default server.
